### ISSUE TITLE
Roadmap for 3.0

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/grafana-pcp#48]
- [X] replace angular with react #38 
- [x] rethink caching strategy #11 
- [X] automatically set unit by datasource #20 
- [x] support derived metrics #13 
- [x] use web worker to poll in background #3 
- [x] use jsonnet to store grafana dashboards #32 
- [X] update polltimeout according to the current poll interval #51
- [X] configurable hostspec #52
